### ISSUE TITLE
copper border bridges pins

### ISSUE THREAD

**Issue by blinkworth1** [macaba/Teensy-3.2-USB#1]
I ordered the board and it came with a pretty copper coloured border (see the photo) ...it turns out that it _is_ copper, and it bridges the D+ and D- surface mount castellated 'pins'.     I guess I should have known before I assembled everything, but it might be worth putting a warning for noobies like me about pretty copper borders.
![wp_20160513_21_09_13_pro](https://cloud.githubusercontent.com/assets/18300974/15243663/191d4f5a-1951-11e6-8cbd-de3c687b2e25.jpg)

**Comment by macaba** [comment]
Thanks for reporting this. I didn't have this on my boards but I know what causes it and I've got a fix that I will publish to OSH park as soon as possible. Sorry about the bridging.

**Comment by blinkworth1** [comment]
Groovy.  if I had been a bit more onto it, I would have spotted it
before I soldered it all up!!

Thanks for taking the time to do this, and offer it free to everyone...

**Comment by macaba** [comment]
https://oshpark.com/shared_projects/C8EaHAAq
